### ISSUE TITLE
Move album art up for LockGlyph

### ISSUE THREAD

**Issue by AppleBetas** [Sticktron/LockGlyphX#13]

**Comment by Sticktron** [comment]
Should move the default position lower when the unlock text is hidden to better accommodate the album art.

Also going to add a setting to hide the page dots, so people can hide the text and dots and move the glyph really low.

**Comment by Sticktron** [comment]
> Should move the default position lower when the unlock text is hidden to better accommodate the album art.

I think we are good on this issue now.
