### ISSUE TITLE
Localize some strings

### ISSUE THREAD

**Issue by AppleBetas** [Sticktron/LockGlyphX#17]
Notably group header labels and the following keys:

`LOCKLABEL_ENABLED_LABEL` = "Show 'Press home to unlock'"
`LOCKLABEL_CUSTOM_TEXT_LABEL` = "Custom text"
`SOUND_FOOTER` = "Choosing 'Theme' will use the default Apple Pay sound if you do not have a theme with a sound enabled."
`SOUND_NONE` = "None"
`SOUND_DEFAULT` = "Theme (default)"
`SOUND_APPLE_PAY` = "Apple Pay"
`SOUND_OLD_APPLE_PAY` = "Classic Apple Pay"
`GENERAL_UNLOCKSNDSELECTION_LABEL` = "Unlock sound"
`ANIM_LOADINGTOGL_LABEL` = "Use loading scan animation"
`ANIM_HOLDTOREADERTOGL_LABEL` = "Use 'Hold to Reader' idle animation"
`ANIM_ONLYDEFAULT_LABEL` = "This animation will only be active if you are using the default Apple Pay theme."

**Comment by Sticktron** [comment]
Created a new issue with a link to a Gist with the master list of translations needed.
Closing.
