### ISSUE TITLE
Won't always open after giving check mark

### ISSUE THREAD

**Issue by DrywallJackson** [Sticktron/LockGlyphX#18]
First off, this tweak is great and I think my problem is not necessarily your fault but is Apple's.
Sometimes when I scan my fingerprint, my phone will get "unlocked", as in it'll let me in if I tap the home button, but it won't /actually/ unlock in the sense that it takes me to my home screen/app I'm in. I think this is more Apple's fault but it's a bit anticlimactic to get the beautiful "ding!" from LockGlpyh but then have to press the home button again.

**Comment by nullpixel** [comment]
Intended and dupe of #2:

the checkmark means it's fine to press home to open

**Comment by AppleBetas** [comment]
Remember that "Rest finger to open" is an Accessibility option in stock iOS and can easily be enabled to restore the old iOS home button behaviour.

**Comment by DrywallJackson** [comment]
Oh, didn't know that. Nice, thanks!

**Comment by AppleBetas** [comment]
Please close this issue
