### ISSUE TITLE
It doesnt unlock after animation on iphone 7 ios 10.1.1

### ISSUE THREAD

**Issue by mr-f0xx** [Sticktron/LockGlyphX#2]
Title

**Comment by AppleBetas** [comment]
It will if you woke the phone with the home button or have "Rest Finger to Open" enabled in Accessibility settings. iOS 10 changed the lock screen, and this is how it's decided that LockGlyph should function to integrate as best as possible.

**Comment by nullpixel** [comment]
@Sticktron close kthnx

**Comment by AppleBetas** [comment]
@Sticktron this is an intentional behaviour and the issue should be closed
