### ISSUE TITLE
Small Issue

### ISSUE THREAD

**Issue by JonathanBroering** [Sticktron/LockGlyphX#24]
Maybe it is kid an iOS stock issue but it appeard after going back from the Theme section. 

http://imgur.com/a/RoPq7

Model: iPhone SE
Version: 64GB
iOS Version: 10.2

Note:
I think it could be triggered by upscale or cask.

**Comment by JonathanBroering** [comment]
Sry for bad English ¯\_(ツ)_/¯

**Comment by Sticktron** [comment]
Does it happen every time? Does it happen to any other tweak's settings?

**Comment by Sticktron** [comment]
isolated incident, closing for now.
