### ISSUE TITLE
Shine animation doesn't work

### ISSUE THREAD

**Issue by AppleBetas** [Sticktron/LockGlyphX#28]

**Comment by Sticktron** [comment]
Can you be more specific? It seems to be working here.

**Comment by AppleBetas** [comment]
The shine animation that accompanies the glyph doesn't seem to be working on my device (10.2, iPhone 6). I had it working in my version so I'll take a look into it later.

**Comment by Sticktron** [comment]
ok, strange. it's definitely working here (10.2, 6s) with default and custom themes.

**Comment by AppleBetas** [comment]
I'm an idiot
