### ISSUE TITLE
Latest GitHub commit still giving me "Error when loading preferences"

### ISSUE THREAD

**Issue by TheNightRider12** [Sticktron/LockGlyphX#36]
When using the latest commit from GitHub I keep getting "Error loading preferences bundle" in the tweak settings in the iPhone settings app. But when I use the one from your repo, it woks fine. Is this a bug?

**Comment by Sticktron** [comment]
Hmm definitely not supposed to be happening, but I can't reproduce this. Try the latest commit.

**Comment by TheNightRider12** [comment]
Still happening. this started after the "Updated to Latest Prefs" or something like "Latest Prefs". But I know when I pulled the latest, the Latest commit at that time was something to do with Latest Prefs. That is when I started having this issue. But I can't find that commit. The version of your repo works fine though.
@Sticktron
