### ISSUE TITLE
LockglyphX Beta 3 tap to unlock stopped working

### ISSUE THREAD

**Issue by brettsloan** [Sticktron/LockGlyphX#38]
Upgraded to beta 3 and now I can't tap to unlock the lockscreen. I just downgraded and it works again! I can provide a tweak list if needed.

**Comment by Sticktron** [comment]
You're right. I'll fix it.

Sent from my iPhone

On Feb 28, 2017, at 10:40 AM, brettsloan <notifications@github.com<mailto:notifications@github.com>> wrote:


Upgraded to beta 3 and now I can't tap to unlock the lockscreen. I just downgraded and it works again! I can provide a tweak list if needed.

**Comment by Sticktron** [comment]
fixed
