### ISSUE TITLE
Sound 

### ISSUE THREAD

**Issue by Adnaan77** [Sticktron/LockGlyphX#4]
Unlock sound doesn't always play. Even though unlock immediately is off.

**Comment by AppleBetas** [comment]
This may be fixed by 	dc8f26b

**Comment by AppleBetas** [comment]
@Adnaan77 is this issue fixed for you in the new version? If so, please close this issue.

**Comment by Adnaan77** [comment]
No it did not fixed

**Comment by AppleBetas** [comment]
What version of the LockGlyphX beta are you using, and do you have your ringer on when it fails to play?

**Comment by Adnaan77** [comment]
I have beta 2.  And yes ringer is on. I figured when you press to unlock it doesn't play sound it unlockes quickly. But when you rest your finger without pressing the sound plays.

**Comment by AppleBetas** [comment]
The sound won't play if the passcode view is visible. Are the numbers to input the passcode visible on the screen when this occurs?

**Comment by Adnaan77** [comment]
No the passcode isn't visible. This is straight unlocking from screen wake

**Comment by AppleBetas** [comment]
Hmm, this is confusing me. Could you tell me the device model, iOS version, if Siri is enabled, if you have "Rest Finger to Open" enabled, and provide me with a list of tweaks you have installed?

**Comment by Adnaan77** [comment]
iPhone 7 iOS 10.1.1 Mach portal jailbreak 
Siri is enabled 
Rest finger to open is off (even when it's on. no sound when pressing home to unlock) 
List of tweakes:
Noctis - eclipse 4 - watusi for WhatsApp- callbar - swipeselection - statusvulx - phantom for Snapchat.

**Comment by Adnaan77** [comment]
Maybe because the iPhone 7 fingerprint is so fast that's why it unlocks  quickly the sound doesn't have time to play. Cuz I tried on i6 10.2 and the sound plays each time cuz the fingerprint  not that fast - although when it unlocks fast the sound doesn't play - which happened twice so far.

**Comment by AppleBetas** [comment]
Does a checkmark appear after it's been unlocked?

**Comment by Adnaan77** [comment]
No. it doesn't.  It unlocks so quickly. Just as if "unlock immediately" feature is on. But it isn't

**Comment by Skizzy34** [comment]
Having the same problem on an iPhone 7 Plus. I figured it wasn't the speed of the unlock, but the sound always played with LockGlyph Beta.

**Comment by Sticktron** [comment]
Are you guys still having problems with the sound in beta 3?

**Comment by Adnaan77** [comment]
Yes

**Comment by Skizzy34** [comment]
Yup.

**Comment by Skizzy34** [comment]
Same for beta 4. Weird that it works in the old beta.

**Comment by Adnaan77** [comment]
Yes I just tested beta 4 same thing. It's really weird that it was good indeed on the old beta that was leaked before lockglyphX

**Comment by AppleBetas** [comment]
It wasn't leaked, it was updated by another developer and released as a beta independently (that developer being me). I'm also contributing to this project and have helped with it in many ways, so I'll take a look later.

**Comment by Skizzy34** [comment]
You want updates for every beta release? Beta 5 is still a no go.

**Comment by Sticktron** [comment]
Moved to evilgoldfish/LockGlyphX

**Comment by Skizzy34** [comment]
It's working for me now. I have mikoto installed and there was a fast unlock setting in there that interfered with LockGlyphX. Turning it of fixed it.

-Scott
